import { ThemeProvider } from "@/components/theme-provider";
import { 
  ModeToggle, 
  Button, 
  Separator, 
  Textarea,
  Label,
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
  Slider
} from "@/components";
import { Github, FileVideo, Upload, Wand2 } from "lucide-react";

export function App() {
  return (
    <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
      <div className='flex flex-col min-h-screen'>
        <header className='flex w-full justify-between px-6 py-3 border-b'>
          <div className='flex justify-center items-center space-x-2 text-xl font-bold'>
            <h1>Upload.ai</h1>
            <span>✨</span>
          </div>

          <div className='flex justify-center items-center space-x-3'>
            <div className='flex justify-center items-center space-x-2 text-sm text-muted-foreground'>
              <span className='italic'>Developed by</span>
              <a 
                href="https://www.linkedin.com/in/fernando-csilva/"
                target="_blank"
                className="font-semibold italic hover:text-gray-300 ease-in-out duration-200"
              >
                @Fernando Silva
              </a>
              <span>🤖</span>
            </div>

            <Separator orientation='vertical' className='h-6' />

            <div className='flex justify-center items-center space-x-4'>
              <a 
                href="https://github.com/Fernandosilvasc/upload-ai-web"
                target="_blank"
              >
                <Button variant='outline' className="flex w-full space-x-2">
                  <Github className='w-4 h-4' />
                  <span>GitHub</span>
                </Button>
              </a>
              <ModeToggle />
            </div>
          </div>
        </header>

        <main className='flex flex-1 p-6 gap-6'>
          <section className='grid grid-rows-2 flex-1 gap-4'>
            <Textarea 
              placeholder={`Insert the AI's prompt...`} 
              className='italic resize-none p-4 leading-relaxed' 
            />
            <Textarea 
              placeholder={`Result generated by the IA...`} 
              className='italic resize-none p-4 leading-relaxed'
            />
          </section>
          
          <aside className='w-80 space-y-6'>
            <form className='w-full space-y-6'>
              <label 
                htmlFor='video'
                className='
                  flex flex-col justify-center items-center
                  border-2 border-dashed rounded-md gap-2 
                  aspect-video cursor-pointer
                  font-semibold text-sm text-muted-foreground hover:text-secondary
                  hover:bg-primary
                '>
                <FileVideo className='w-6 h-6' />
                Upload video
              </label>

              <input type="file" id='video' accept='video/mp4' className='sr-only' />

              <Separator />

              <div className='space-y-2'>
                <Label htmlFor='transcription_prompt' className=''>Transcription prompt</Label>
                <Textarea 
                  id='transcription_prompt'
                  placeholder='Insert the video keywords separated by comma (...,)'
                  className='h-20 leading-relaxed italic text-sm resize-none'
                />
              </div>

              <Button
                type='submit'
                className='w-full gap-2 text-sm
              '>
                {'Load the video'}
                <Upload className='w-4 h-4' />
              </Button>
            </form>

            <Separator />

            <form className='w-full space-y-6'>
              <div className='space-y-2'>
                <Label>Prompt</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder='Select the prompt...' />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value='title'>Youtube title</SelectItem>
                    <SelectItem value='description'>Youtube Description</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <Separator />

              <div className='space-y-2'>
                <Label>Model</Label>
                <Select disabled defaultValue='gpt-3.5'>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value='gpt-3.5'>GPT 3.5-turbo 16k</SelectItem>
                  </SelectContent>
                </Select>
                <span className='flex text-xs text-muted-foreground italic leading-relaxed'>We will be providing more AI core options as soon as possible.</span>
              </div>

              <Separator />

              <div className='space-y-4'>
                <Label>Temperature</Label>
                <Slider min={0} max={1} step={0.1} />
                <span className='flex text-xs text-muted-foreground italic leading-relaxed'>Higher values tend to make the result more creative, but there may be inconsistency in the response.</span>
              </div>

              <Separator />

              <Button
                type='submit'
                className='w-full gap-2 text-sm
              '>
                {'Execute'}
                <Wand2 className='w-4 h-4' />
              </Button>
            </form>
          </aside>
        </main>

        <footer className='w-full flex justify-start items-center text-sm text-muted-foreground p-3 border-t gap-2'>
          <span className='text-primary'>{`Note: `}</span>
          {`You can use the variable `}
          <code className='text-primary'>{`{transcription}`}</code>
          {` inside your prompt to insert the transcript's content in the selected video!`}
        </footer>
      </div>
    </ThemeProvider>
  )
}

export default App
