import { Textarea } from "@/components";

interface IPromptTextAreaContainerProps {
  promptInputValue: string;
  promptOutputValue: string;
  handleOnChangeValue: any
}

export function PromptTextAreaContainer({ 
  promptInputValue,
  promptOutputValue, 
  handleOnChangeValue 
}: IPromptTextAreaContainerProps) {

  return (
    <section className='grid grid-rows-2 flex-1 gap-4'>
      <Textarea
        placeholder={`Insert the AI's prompt...`} 
        className='italic resize-none p-4 leading-relaxed'
        value={promptInputValue}
        onChange={handleOnChangeValue} 
      />
      <Textarea 
        placeholder={`Result generated by the IA...`} 
        className='italic resize-none p-4 leading-relaxed'
        value={promptOutputValue}
      />
    </section>
  )
}
